### ISSUE TITLE
Memory leak if there's no reply?

### ISSUE THREAD

**Issue by ghost** [zbjornson/ndns#5]
If a response is never received, does that mean that the event listener stays around forever? Is there any kind of timeout mechanism supported?

Thanks for this. Looks like a great library.

**Comment by zbjornson** [comment]
Hm, yes, good point! Looks like we need to add a timeout and an `"error"` event handler for the socket. Will try to do that this coming weekend. Also happy to review a PR if you're up for making one.

**Comment by zbjornson** [comment]
Added a configurable timeout that defaults to 10s, along with a new client example:

https://github.com/primitybio/bindns/blob/ce9ac1cc91140329230140417ee3e7f3fbc326e5/examples/simple-client.js#L15-L21

Thanks for finding that issue.

**Comment by ghost** [comment]
Fantastic. Thank you!
